### PR TITLE
added a list of projects and some of my solutions

### PR DESCRIPTION
**Pull request by elvongray**
Saw a list of projects online, thought you might be interested. I solved four of them in python. I'm interested in your daily-scripts repo, will love to contribute to the repo with my own scripts also.

### CODE REVIEW

**Comment by gnerkus** [comment]
Good afternoon,

Could you move your solutions into the folders that match their file types? For example, you could move the fibonacci solution to the python folder.

Nice work and thanks for cloning my puny repo.

**Comment by gnerkus** [comment]
I'm very much interested in that list of projects. The daily scripts are just random solutions to problems I've encountered at work.

**Comment by elvongray** [comment]
I have moved the solutions. Should I use a naming convention to differentiate it from yours.

**Comment by gnerkus** [comment]
A naming convention would be nice.

Thank you.

**Comment by elvongray** [comment]
The naming convention I'm using is to precede each file of my solution with eni_.

**Pull request merged**
